### ISSUE TITLE
problems about convmixer

### ISSUE THREAD

**Issue by xinchenduobian** [kentaroy47/vision-transformers-cifar10#12]
Hello, when I use ConvMixer, I always have the problem of conv2d(): argument 'padding' (position 5) must be tuple of ints, not str

**Comment by xinchenduobian** [comment]
Do you know it？ Thanks a lot

**Comment by kentaroy47** [comment]
Really? It works fine in my env.
Can you tell me your torch version?

**Comment by xinchenduobian** [comment]
my torch is 1.7.0 in cuda 11.0



---- Replied Message ----
| From | Kentaro ***@***.***> |
| Date | 05/30/2022 08:46 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [kentaroy47/vision-transformers-cifar10] problems about convmixer (Issue #12) |

Really? It works fine in my env.
Can you tell me your torch version?

**Comment by xinchenduobian** [comment]
I try it in torch 1.10.0, and it can work now. Thanks!
