### ISSUE TITLE
MLPMixer result

### ISSUE THREAD

**Issue by ShijianXu** [kentaroy47/vision-transformers-cifar10#19]
Hello, 
I have a question about the MLPMixer result. I trained multiple versions of the MLPMixer model, but none of them can achieve the 88% accuracy. Can you provide the detailed configurations you used for training this model? It will be very helpful.
Best regards

**Comment by kentaroy47** [comment]
The 88% mlp mixer was trained with this. I think the lr is different from ViT
`train_cifar10.py --net mlpmixer --lr 1e-3 --aug --n_epochs 500 --bs 2048`
