### ISSUE TITLE
swin acc can't get  90%

### ISSUE THREAD

**Issue by BlueSkyyyyyy** [kentaroy47/vision-transformers-cifar10#24]
I run "python train_cifar10.py --net swin --n_epochs 400" either with 1GPU or 8GPU all get acc about 84.5%.  Can you share your config ?

**Comment by BlueSkyyyyyy** [comment]
I known why

**Comment by kentaroy47** [comment]
why was it?

**Comment by darrenzhang1007** [comment]
> I known why

hello,bro. I met same problem, Can u tell me the reason？Thanks

**Comment by BlueSkyyyyyy** [comment]
> > I known why
> 
> hello,bro. I met same problem, Can u tell me the reason？Thanks
bool(~args.noamp) can not use as this.  replace with use_amp = not args.noamp . some arguments may alslo have not exact
