### ISSUE TITLE
Some Questions About Training and Inference.

### ISSUE THREAD

**Issue by srdfjy** [kentaroy47/vision-transformers-cifar10#27]
Hi

1，I want to train on the CPU, but I get the following warning: "UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available. Disabling."

2，How to perform model inference, such as MLP-Mixer or ResNet18 with RandAugment?

**Comment by kentaroy47** [comment]
> 1，I want to train on the CPU, but I get the following warning: "UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available. Disabling."

this is a warning, so it should be fine.

> 2，How to perform model inference, such as MLP-Mixer or ResNet18 with RandAugment?

do you mean model training? you don't turn on RandAug on inference.

If training, RandAug is used as a default
