### ISSUE TITLE
Swin unable to reach 90%

### ISSUE THREAD

**Issue by yuelinxin** [kentaroy47/vision-transformers-cifar10#31]
Hi, I have been trying to get Swin-tiny to go to 90% acc on cifar10 for a long time, but I haven't been able to do so. I've tried adjusting some hyper-parameters and augmentation, but it's always below 90%, the highest I got is around 86%. Could you provide the hyper-parameter setting you used to get to 90%? Or could you provide the training log for swin_t? Thank you.

**Comment by kentaroy47** [comment]
`python train_cifar10.py --net swin --n_epochs 400`
are you trying this? can you share your training log?

I could only find the one with epoch=200, but it reaches 88%
https://api.wandb.ai/links/arutema47/rcqazxqh

**Comment by kentaroy47** [comment]
Maybe the trick is I set the `--lr 1e-4`?

**Comment by yuelinxin** [comment]
Thank you, i will try this first.

**Comment by yuelinxin** [comment]
Hi, I've tried using this: `python train_cifar10.py --net swin --n_epochs 400 --lr 1e-4`, and I only got 84%, I don't believe I have changed anything in the code, here's my training log:
[log_swin_patch4.txt](https://github.com/kentaroy47/vision-transformers-cifar10/files/14157956/log_swin_patch4.txt)

**Comment by kentaroy47** [comment]
Ok, I will look into this. Haven't tried swin for a long time.

2024年2月5日(月) 3:59 Yuelin Xin ***@***.***>:

**Comment by kentaroy47** [comment]
thanks for pointing out, the training codes was not using randomaug as default.
i fixed this up in the last commit and if you pull, it should reach 90%.

**Comment by kentaroy47** [comment]
`python train_cifar10.py --net swin --n_epochs 400` this should be enough.

**Comment by yuelinxin** [comment]
Thank you!
