### ISSUE TITLE
Is it from scratch?

### ISSUE THREAD

**Issue by free001style** [kentaroy47/vision-transformers-cifar10#33]
Hi! Do I understand correctly that you were using pretrained models? If not, I don't see it in your code.

**Comment by kentaroy47** [comment]
Default settings use scratch models.

2024年9月12日(木) 5:05 Ilya Drobyshevskiy ***@***.***>:

**Comment by kentaroy47** [comment]
python train_cifar10.py --net vit_tim

This uses pertained models.

2024年9月12日(木) 8:18 ***@***.*** ***@***.***>:
