### ISSUE TITLE
Why the code cannot reach a top1 accuracy of above 97% in cifar10?

### ISSUE THREAD

**Issue by zhoufengfan** [kentaroy47/vision-transformers-cifar10#5]
The official paper of vit can reach a top1 accuracy of above 97% in cifar10.

**Comment by josueortc** [comment]
I think the original ViT paper was pretrained on ImageNet?

**Comment by Apostatee** [comment]
This code was trained from scratch

**Comment by kentaroy47** [comment]
![image](https://user-images.githubusercontent.com/39611941/124216813-05f93d00-db32-11eb-8020-00c65ca579b8.png)
