### ISSUE TITLE
80% accuracy? 

### ISSUE THREAD

**Issue by bismillahkani** [kentaroy47/vision-transformers-cifar10#6]
How were you able to achieve 80% accuracy for CIFAR-10 by training from scratch? Is it Top-1 or Top-5 accuracy? If Top-1 can you please share the train settings to achieve 80% Top-1 accuracy?

**Comment by kentaroy47** [comment]
@bismillahkani 
you should be able to achieve 80% top-1 with `python train_cifar10.py`.

**Comment by slerman12** [comment]
I get 60% from running the script

**Comment by slerman12** [comment]
We have CUDA 10.2. could be a precision error or something?
