### ISSUE TITLE
Are these training or test accuracies?

### ISSUE THREAD

**Issue by slerman12** [kentaroy47/vision-transformers-cifar10#7]

**Comment by kentaroy47** [comment]
It's test accuracy

**Comment by slerman12** [comment]
Are they? I'm not getting reported results from running the provided script

**Comment by slerman12** [comment]
50 epochs? 80% test accuracy?

**Comment by kentaroy47** [comment]
Oops, you need this commands
`train_cifar10.py --aug --n_epochs 200 --lr 0.0001`

Here is the train log.

https://wandb.ai/arutema47/cifar10-challange/reports/Untitled-Report--VmlldzoxNjU3MTU2?accessToken=3y3ib62e8b9ed2m2zb22dze8955fwuhljl5l4po1d5a3u9b7yzek1tz7a0d4i57r

**Comment by kentaroy47** [comment]
I updated the readme, sorry for the confusion
